run:
  tests: true
  timeout: 5m

output:
  formats:
    - format: tab
      path: stdout

linters:
  enable:
    - asciicheck
    - dogsled
    - errcheck
    - exportloopref
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  lll:
    line-length: 400
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  gomodguard:
    blocked:
      versions: # List of blocked module version constraints
        - https://github.com/etcd-io/etcd: # Blocked module with version constraint
            version: ">= 3.4.10 || ~3.3.23" # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-15114; CVE-2020-15136; CVE-2020-15115" # Reason why the version constraint exists. (Optional)
        - https://github.com/dgrijalva/jwt-go: # Blocked module with version constraint
            version: ">= 4.0.0-preview1" # Version constraint, see https://github.com/Masterminds/semver#basic-comparisons
            reason: "CVE-2020-26160" # Reason why the version constraint exists. (Optional)

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
    - x/storage/
