// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mechain/challenge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryAttestedChallengeRequest is request type for the Query/AttestedChallenge RPC method.
type QueryAttestedChallengeRequest struct {
	// The id of the challenge.
	ChallengeId uint64 `protobuf:"varint,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
}

func (m *QueryAttestedChallengeRequest) Reset()         { *m = QueryAttestedChallengeRequest{} }
func (m *QueryAttestedChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestedChallengeRequest) ProtoMessage()    {}
func (*QueryAttestedChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{2}
}
func (m *QueryAttestedChallengeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestedChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestedChallengeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestedChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestedChallengeRequest.Merge(m, src)
}
func (m *QueryAttestedChallengeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestedChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestedChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestedChallengeRequest proto.InternalMessageInfo

func (m *QueryAttestedChallengeRequest) GetChallengeId() uint64 {
	if m != nil {
		return m.ChallengeId
	}
	return 0
}

// QueryAttestedChallengeResponse is response type for the Query/AttestedChallenge RPC method.
type QueryAttestedChallengeResponse struct {
	Challenge *AttestedChallenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
}

func (m *QueryAttestedChallengeResponse) Reset()         { *m = QueryAttestedChallengeResponse{} }
func (m *QueryAttestedChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestedChallengeResponse) ProtoMessage()    {}
func (*QueryAttestedChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{3}
}
func (m *QueryAttestedChallengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestedChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestedChallengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestedChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestedChallengeResponse.Merge(m, src)
}
func (m *QueryAttestedChallengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestedChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestedChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestedChallengeResponse proto.InternalMessageInfo

func (m *QueryAttestedChallengeResponse) GetChallenge() *AttestedChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

// QueryLatestAttestedChallengesRequest is request type for the Query/LatestAttestedChallenges RPC method.
type QueryLatestAttestedChallengesRequest struct {
}

func (m *QueryLatestAttestedChallengesRequest) Reset()         { *m = QueryLatestAttestedChallengesRequest{} }
func (m *QueryLatestAttestedChallengesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestAttestedChallengesRequest) ProtoMessage()    {}
func (*QueryLatestAttestedChallengesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{4}
}
func (m *QueryLatestAttestedChallengesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestAttestedChallengesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestAttestedChallengesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestAttestedChallengesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestAttestedChallengesRequest.Merge(m, src)
}
func (m *QueryLatestAttestedChallengesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestAttestedChallengesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestAttestedChallengesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestAttestedChallengesRequest proto.InternalMessageInfo

// QueryLatestAttestedChallengesResponse is response type for the Query/LatestAttestedChallenges RPC method.
type QueryLatestAttestedChallengesResponse struct {
	Challenges []*AttestedChallenge `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
}

func (m *QueryLatestAttestedChallengesResponse) Reset()         { *m = QueryLatestAttestedChallengesResponse{} }
func (m *QueryLatestAttestedChallengesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestAttestedChallengesResponse) ProtoMessage()    {}
func (*QueryLatestAttestedChallengesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{5}
}
func (m *QueryLatestAttestedChallengesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestAttestedChallengesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestAttestedChallengesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestAttestedChallengesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestAttestedChallengesResponse.Merge(m, src)
}
func (m *QueryLatestAttestedChallengesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestAttestedChallengesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestAttestedChallengesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestAttestedChallengesResponse proto.InternalMessageInfo

func (m *QueryLatestAttestedChallengesResponse) GetChallenges() []*AttestedChallenge {
	if m != nil {
		return m.Challenges
	}
	return nil
}

// QueryInturnAttestationSubmitterRequest is request type for the Query/InturnAttestationSubmitter RPC method.
type QueryInturnAttestationSubmitterRequest struct {
}

func (m *QueryInturnAttestationSubmitterRequest) Reset() {
	*m = QueryInturnAttestationSubmitterRequest{}
}
func (m *QueryInturnAttestationSubmitterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInturnAttestationSubmitterRequest) ProtoMessage()    {}
func (*QueryInturnAttestationSubmitterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{6}
}
func (m *QueryInturnAttestationSubmitterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInturnAttestationSubmitterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInturnAttestationSubmitterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInturnAttestationSubmitterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInturnAttestationSubmitterRequest.Merge(m, src)
}
func (m *QueryInturnAttestationSubmitterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInturnAttestationSubmitterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInturnAttestationSubmitterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInturnAttestationSubmitterRequest proto.InternalMessageInfo

// QueryInturnAttestationSubmitterResponse is response type for the Query/InturnAttestationSubmitter RPC method.
type QueryInturnAttestationSubmitterResponse struct {
	BlsPubKey      string          `protobuf:"bytes,1,opt,name=bls_pub_key,json=blsPubKey,proto3" json:"bls_pub_key,omitempty"`
	SubmitInterval *SubmitInterval `protobuf:"bytes,2,opt,name=submit_interval,json=submitInterval,proto3" json:"submit_interval,omitempty"`
}

func (m *QueryInturnAttestationSubmitterResponse) Reset() {
	*m = QueryInturnAttestationSubmitterResponse{}
}
func (m *QueryInturnAttestationSubmitterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInturnAttestationSubmitterResponse) ProtoMessage()    {}
func (*QueryInturnAttestationSubmitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{7}
}
func (m *QueryInturnAttestationSubmitterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInturnAttestationSubmitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInturnAttestationSubmitterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInturnAttestationSubmitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInturnAttestationSubmitterResponse.Merge(m, src)
}
func (m *QueryInturnAttestationSubmitterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInturnAttestationSubmitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInturnAttestationSubmitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInturnAttestationSubmitterResponse proto.InternalMessageInfo

func (m *QueryInturnAttestationSubmitterResponse) GetBlsPubKey() string {
	if m != nil {
		return m.BlsPubKey
	}
	return ""
}

func (m *QueryInturnAttestationSubmitterResponse) GetSubmitInterval() *SubmitInterval {
	if m != nil {
		return m.SubmitInterval
	}
	return nil
}

// SubmitInterval holds start and end (exclusive) (i.e., [start, end)) time of in turn attestation.
type SubmitInterval struct {
	Start uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *SubmitInterval) Reset()         { *m = SubmitInterval{} }
func (m *SubmitInterval) String() string { return proto.CompactTextString(m) }
func (*SubmitInterval) ProtoMessage()    {}
func (*SubmitInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c9c5d5102a185, []int{8}
}
func (m *SubmitInterval) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitInterval.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitInterval.Merge(m, src)
}
func (m *SubmitInterval) XXX_Size() int {
	return m.Size()
}
func (m *SubmitInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitInterval.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitInterval proto.InternalMessageInfo

func (m *SubmitInterval) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SubmitInterval) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mechain.challenge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mechain.challenge.QueryParamsResponse")
	proto.RegisterType((*QueryAttestedChallengeRequest)(nil), "mechain.challenge.QueryAttestedChallengeRequest")
	proto.RegisterType((*QueryAttestedChallengeResponse)(nil), "mechain.challenge.QueryAttestedChallengeResponse")
	proto.RegisterType((*QueryLatestAttestedChallengesRequest)(nil), "mechain.challenge.QueryLatestAttestedChallengesRequest")
	proto.RegisterType((*QueryLatestAttestedChallengesResponse)(nil), "mechain.challenge.QueryLatestAttestedChallengesResponse")
	proto.RegisterType((*QueryInturnAttestationSubmitterRequest)(nil), "mechain.challenge.QueryInturnAttestationSubmitterRequest")
	proto.RegisterType((*QueryInturnAttestationSubmitterResponse)(nil), "mechain.challenge.QueryInturnAttestationSubmitterResponse")
	proto.RegisterType((*SubmitInterval)(nil), "mechain.challenge.SubmitInterval")
}

func init() { proto.RegisterFile("mechain/challenge/query.proto", fileDescriptor_123c9c5d5102a185) }

var fileDescriptor_123c9c5d5102a185 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xfb, 0x27, 0x75, 0x8a, 0x0a, 0x5d, 0x7a, 0x68, 0x0d, 0x35, 0xd4, 0xea, 0x9f, 0x10,
	0xcd, 0x92, 0x22, 0xd4, 0xc2, 0x8d, 0x80, 0x90, 0x0a, 0x08, 0x15, 0x73, 0xe3, 0x62, 0xad, 0x93,
	0x95, 0x6b, 0x61, 0x7b, 0x5d, 0xef, 0x3a, 0x22, 0x1c, 0x79, 0x02, 0x24, 0xc4, 0x33, 0xf0, 0x20,
	0x70, 0xe8, 0x81, 0x43, 0x25, 0x2e, 0x9c, 0x10, 0x4a, 0x78, 0x10, 0xe4, 0xdd, 0x8d, 0x21, 0xd8,
	0x56, 0x28, 0x97, 0xc8, 0x3b, 0xf3, 0x7d, 0xdf, 0x7c, 0x33, 0x1e, 0x6f, 0x60, 0x2d, 0xa2, 0x9d,
	0x63, 0x12, 0xc4, 0xb8, 0x73, 0x4c, 0xc2, 0x90, 0xc6, 0x3e, 0xc5, 0x27, 0x19, 0x4d, 0xfb, 0xcd,
	0x24, 0x65, 0x82, 0xa1, 0x25, 0x9d, 0x6e, 0x16, 0x69, 0xf3, 0x46, 0x87, 0xf1, 0x88, 0x71, 0xec,
	0x11, 0xae, 0xb1, 0xb8, 0xd7, 0xf2, 0xa8, 0x20, 0x2d, 0x9c, 0x10, 0x3f, 0x88, 0x89, 0x08, 0x58,
	0xac, 0xe8, 0xe6, 0xaa, 0xc2, 0xba, 0xf2, 0x84, 0xd5, 0x41, 0xa7, 0x96, 0x7d, 0xe6, 0x33, 0x15,
	0xcf, 0x9f, 0x74, 0xf4, 0xaa, 0xcf, 0x98, 0x1f, 0x52, 0x4c, 0x92, 0x00, 0x93, 0x38, 0x66, 0x42,
	0xaa, 0x8d, 0x38, 0x56, 0xd9, 0x6c, 0x42, 0x52, 0x12, 0x8d, 0xf2, 0x15, 0xcd, 0x88, 0x7e, 0x42,
	0x75, 0xda, 0x5e, 0x06, 0xf4, 0x3c, 0xf7, 0x7b, 0x24, 0x39, 0x0e, 0x3d, 0xc9, 0x28, 0x17, 0xf6,
	0x33, 0xb8, 0x3c, 0x16, 0xe5, 0x09, 0x8b, 0x39, 0x45, 0xfb, 0x30, 0xa7, 0xb4, 0x57, 0x8c, 0xeb,
	0xc6, 0xce, 0xc2, 0xde, 0x6a, 0xb3, 0x34, 0x8a, 0xa6, 0xa2, 0xb4, 0x67, 0x4e, 0xbf, 0x5f, 0x6b,
	0x38, 0x1a, 0x6e, 0xb7, 0x61, 0x4d, 0xea, 0xdd, 0x17, 0x82, 0x72, 0x41, 0xbb, 0x0f, 0x46, 0x70,
	0x5d, 0x10, 0xad, 0xc3, 0x85, 0x42, 0xc2, 0x0d, 0xba, 0x52, 0x7f, 0xc6, 0x59, 0x28, 0x62, 0x87,
	0x5d, 0xbb, 0x0b, 0x56, 0x9d, 0x86, 0xb6, 0xd7, 0x86, 0xf9, 0x82, 0xa0, 0x1d, 0x6e, 0x54, 0x38,
	0x2c, 0x0b, 0xfc, 0xa6, 0xd9, 0x5b, 0xb0, 0x21, 0xab, 0x3c, 0x25, 0x39, 0xa8, 0x04, 0x2d, 0x26,
	0x14, 0xc1, 0xe6, 0x04, 0x9c, 0x36, 0xf5, 0x10, 0xa0, 0x50, 0xcf, 0xe7, 0x36, 0xfd, 0xcf, 0xae,
	0xfe, 0xe0, 0xd9, 0x3b, 0xb0, 0x25, 0xcb, 0x1d, 0xc6, 0x22, 0x4b, 0x63, 0x85, 0x95, 0x6b, 0xf0,
	0x22, 0xf3, 0xa2, 0x40, 0x08, 0x9a, 0x8e, 0x8c, 0x7d, 0x30, 0x60, 0x7b, 0x22, 0x54, 0x7b, 0xb3,
	0x60, 0xc1, 0x0b, 0xb9, 0x9b, 0x64, 0x9e, 0xfb, 0x8a, 0xf6, 0xe5, 0xc8, 0xe6, 0x9d, 0x79, 0x2f,
	0xe4, 0x47, 0x99, 0xf7, 0x84, 0xf6, 0xd1, 0x63, 0xb8, 0xc8, 0x25, 0xc9, 0x0d, 0x62, 0x41, 0xd3,
	0x1e, 0x09, 0x57, 0xa6, 0xe4, 0x58, 0xd7, 0x2b, 0x1a, 0x50, 0xf2, 0x87, 0x1a, 0xe8, 0x2c, 0xf2,
	0xb1, 0xb3, 0x7d, 0x00, 0x8b, 0xe3, 0x08, 0xb4, 0x0c, 0xb3, 0x5c, 0x90, 0x54, 0xe8, 0x97, 0xad,
	0x0e, 0xe8, 0x12, 0x4c, 0xd3, 0xb8, 0x2b, 0xeb, 0xcc, 0x38, 0xf9, 0xe3, 0xde, 0xa7, 0x59, 0x98,
	0x95, 0x1d, 0xa1, 0x37, 0x30, 0xa7, 0xd6, 0x0b, 0x6d, 0x56, 0x18, 0x28, 0xef, 0xb1, 0xb9, 0x35,
	0x09, 0xa6, 0x06, 0x61, 0xaf, 0xbf, 0xfd, 0xfa, 0xf3, 0xfd, 0xd4, 0x15, 0xb4, 0x8a, 0xeb, 0xbe,
	0x26, 0xf4, 0xd1, 0x80, 0xa5, 0xd2, 0x3b, 0x42, 0xb7, 0xea, 0x0a, 0xd4, 0x6d, 0xba, 0xd9, 0x3a,
	0x07, 0x43, 0xbb, 0xdb, 0x95, 0xee, 0xb6, 0xd1, 0x66, 0x85, 0x3b, 0xa2, 0x59, 0x6e, 0x11, 0x42,
	0x9f, 0x0d, 0x58, 0xa9, 0x5b, 0x4b, 0xb4, 0x5f, 0x57, 0x7e, 0xc2, 0xc2, 0x9b, 0x07, 0xe7, 0x27,
	0x6a, 0xfb, 0x77, 0xa4, 0x7d, 0x8c, 0x76, 0x2b, 0xec, 0x87, 0x92, 0xec, 0x96, 0xbb, 0xe0, 0xe8,
	0x8b, 0x01, 0x66, 0xfd, 0x0e, 0xa3, 0xbb, 0x75, 0x7e, 0x26, 0x7e, 0x22, 0xe6, 0xbd, 0xff, 0xa1,
	0xea, 0x66, 0xf6, 0x65, 0x33, 0x2d, 0x84, 0x2b, 0x9a, 0x09, 0x24, 0x5d, 0x37, 0x23, 0xf9, 0x2e,
	0x1f, 0x09, 0xb4, 0x1f, 0x9d, 0x0e, 0x2c, 0xe3, 0x6c, 0x60, 0x19, 0x3f, 0x06, 0x96, 0xf1, 0x6e,
	0x68, 0x35, 0xce, 0x86, 0x56, 0xe3, 0xdb, 0xd0, 0x6a, 0xbc, 0xbc, 0xe9, 0x07, 0xe2, 0x38, 0xf3,
	0x9a, 0x1d, 0x16, 0x61, 0xda, 0xcb, 0xff, 0x46, 0xd4, 0x6f, 0xaf, 0xb5, 0x87, 0x5f, 0xff, 0x7d,
	0x6d, 0x7b, 0x73, 0xf2, 0xde, 0xbe, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xaf, 0xce, 0x0e,
	0xa5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries the attested challenge by challenge id.
	AttestedChallenge(ctx context.Context, in *QueryAttestedChallengeRequest, opts ...grpc.CallOption) (*QueryAttestedChallengeResponse, error)
	// Queries the latest attested challenges.
	LatestAttestedChallenges(ctx context.Context, in *QueryLatestAttestedChallengesRequest, opts ...grpc.CallOption) (*QueryLatestAttestedChallengesResponse, error)
	// Queries the inturn challenger.
	InturnAttestationSubmitter(ctx context.Context, in *QueryInturnAttestationSubmitterRequest, opts ...grpc.CallOption) (*QueryInturnAttestationSubmitterResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mechain.challenge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AttestedChallenge(ctx context.Context, in *QueryAttestedChallengeRequest, opts ...grpc.CallOption) (*QueryAttestedChallengeResponse, error) {
	out := new(QueryAttestedChallengeResponse)
	err := c.cc.Invoke(ctx, "/mechain.challenge.Query/AttestedChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestAttestedChallenges(ctx context.Context, in *QueryLatestAttestedChallengesRequest, opts ...grpc.CallOption) (*QueryLatestAttestedChallengesResponse, error) {
	out := new(QueryLatestAttestedChallengesResponse)
	err := c.cc.Invoke(ctx, "/mechain.challenge.Query/LatestAttestedChallenges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InturnAttestationSubmitter(ctx context.Context, in *QueryInturnAttestationSubmitterRequest, opts ...grpc.CallOption) (*QueryInturnAttestationSubmitterResponse, error) {
	out := new(QueryInturnAttestationSubmitterResponse)
	err := c.cc.Invoke(ctx, "/mechain.challenge.Query/InturnAttestationSubmitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries the attested challenge by challenge id.
	AttestedChallenge(context.Context, *QueryAttestedChallengeRequest) (*QueryAttestedChallengeResponse, error)
	// Queries the latest attested challenges.
	LatestAttestedChallenges(context.Context, *QueryLatestAttestedChallengesRequest) (*QueryLatestAttestedChallengesResponse, error)
	// Queries the inturn challenger.
	InturnAttestationSubmitter(context.Context, *QueryInturnAttestationSubmitterRequest) (*QueryInturnAttestationSubmitterResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AttestedChallenge(ctx context.Context, req *QueryAttestedChallengeRequest) (*QueryAttestedChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestedChallenge not implemented")
}
func (*UnimplementedQueryServer) LatestAttestedChallenges(ctx context.Context, req *QueryLatestAttestedChallengesRequest) (*QueryLatestAttestedChallengesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestAttestedChallenges not implemented")
}
func (*UnimplementedQueryServer) InturnAttestationSubmitter(ctx context.Context, req *QueryInturnAttestationSubmitterRequest) (*QueryInturnAttestationSubmitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InturnAttestationSubmitter not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.challenge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AttestedChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestedChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AttestedChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.challenge.Query/AttestedChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AttestedChallenge(ctx, req.(*QueryAttestedChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestAttestedChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestAttestedChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestAttestedChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.challenge.Query/LatestAttestedChallenges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestAttestedChallenges(ctx, req.(*QueryLatestAttestedChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InturnAttestationSubmitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInturnAttestationSubmitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InturnAttestationSubmitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.challenge.Query/InturnAttestationSubmitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InturnAttestationSubmitter(ctx, req.(*QueryInturnAttestationSubmitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mechain.challenge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AttestedChallenge",
			Handler:    _Query_AttestedChallenge_Handler,
		},
		{
			MethodName: "LatestAttestedChallenges",
			Handler:    _Query_LatestAttestedChallenges_Handler,
		},
		{
			MethodName: "InturnAttestationSubmitter",
			Handler:    _Query_InturnAttestationSubmitter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mechain/challenge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAttestedChallengeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestedChallengeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestedChallengeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChallengeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ChallengeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttestedChallengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestedChallengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestedChallengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Challenge != nil {
		{
			size, err := m.Challenge.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLatestAttestedChallengesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestAttestedChallengesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestAttestedChallengesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestAttestedChallengesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestAttestedChallengesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestAttestedChallengesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Challenges) > 0 {
		for iNdEx := len(m.Challenges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Challenges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryInturnAttestationSubmitterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInturnAttestationSubmitterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInturnAttestationSubmitterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInturnAttestationSubmitterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInturnAttestationSubmitterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInturnAttestationSubmitterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubmitInterval != nil {
		{
			size, err := m.SubmitInterval.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.BlsPubKey) > 0 {
		i -= len(m.BlsPubKey)
		copy(dAtA[i:], m.BlsPubKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BlsPubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubmitInterval) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitInterval) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitInterval) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.End != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x10
	}
	if m.Start != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAttestedChallengeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengeId != 0 {
		n += 1 + sovQuery(uint64(m.ChallengeId))
	}
	return n
}

func (m *QueryAttestedChallengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Challenge != nil {
		l = m.Challenge.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLatestAttestedChallengesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestAttestedChallengesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Challenges) > 0 {
		for _, e := range m.Challenges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryInturnAttestationSubmitterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInturnAttestationSubmitterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BlsPubKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.SubmitInterval != nil {
		l = m.SubmitInterval.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *SubmitInterval) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Start != 0 {
		n += 1 + sovQuery(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovQuery(uint64(m.End))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestedChallengeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestedChallengeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestedChallengeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeId", wireType)
			}
			m.ChallengeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestedChallengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestedChallengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestedChallengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Challenge == nil {
				m.Challenge = &AttestedChallenge{}
			}
			if err := m.Challenge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestAttestedChallengesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestAttestedChallengesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestAttestedChallengesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestAttestedChallengesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestAttestedChallengesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestAttestedChallengesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenges = append(m.Challenges, &AttestedChallenge{})
			if err := m.Challenges[len(m.Challenges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInturnAttestationSubmitterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInturnAttestationSubmitterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInturnAttestationSubmitterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInturnAttestationSubmitterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInturnAttestationSubmitterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInturnAttestationSubmitterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlsPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlsPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubmitInterval == nil {
				m.SubmitInterval = &SubmitInterval{}
			}
			if err := m.SubmitInterval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitInterval) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitInterval: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitInterval: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
