# For tester
name: Deploy for testint
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zkmelabs/mechain:test
          cache-to: type=gha
          cache-from: type=gha


  deploy-with-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV0_SERVER_HOST }}
          username: user
          password: ${{ secrets.DEV0_SERVER_PASSWORD }}
          script: |
            cd /tmp/deploy/k8s-hk-rke2/mechain-helm-charts
            echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig.yaml
            helm --kubeconfig kubeconfig.yaml -n mechain-test upgrade --install mechain-validator mechain-validator -f values_testint.yaml --wait
