# For release
name: Release for testnet
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+*' # e.g v1.2.3-alpha.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  make_tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get Github Tag
        id: meta
        run: |
          echo "tag=$(git describe --always --tags --match='v*')" >> "$GITHUB_OUTPUT"

  publish_image:
    name: Publish Docker Image
    uses: './.github/workflows/docker-publish.yml'
    needs:
      - make_tags
    secrets: inherit
    with:
      tags: "zkmelabs/mechain:latest, zkmelabs/mechain:${{ needs.make_tags.outputs.tag }}"
      publish_tag: false

