# For developer testing
name: Build Docker
on:
  push:
    branches:
      - cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # References: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'cicd'

      - name: Compile and Docker Build
        run: make build-docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      # todo: using docker/build-push-action, Reference: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Push to Docker Hub
        run: make push-docker
