name: Publish to Docker Hub

on:
  workflow_call:
    inputs:
      tags:
        description: Image tags, example. zkmelabs/mechain:develop
        required: true
        type: string
      publish_tag:
        description: Whether to publish tags.
        required: false
        type: boolean
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git fetch everything
        run: git fetch --prune --unshallow

      - name: Get Github tag
        id: meta
        run: |
          if ${{ inputs.publish_tag }}; then
            echo "${{ inputs.tags }}, zkmelabs/mechain:$(git describe --always --tags --match='v*')" >> "$GITHUB_OUTPUT"
          else
            echo "tags=${{ inputs.tags }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
