name: markdown lint
# Lint runs golangci-lint over the entire Evmos repository This workflow is
# run on every pull request and push to main The `golangci` will pass without
# running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  markdown-lint:
    name: Run markdown-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.md
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.yml
          ignore_path: .markdownlintignore
        # Check only if there are differences in the source code
        if: env.GIT_DIFF
